// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      // case TargetPlatform.android:
      //   return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // static const FirebaseOptions android = FirebaseOptions(
  //   apiKey: 'AIzaSyDx20MMXkbCgtcvneH7drGS8JMQ6uiG_YI',
  //   appId: '1:296859940615:android:4579f4cfb3036db04bb7a2',
  //   messagingSenderId: '296859940615',
  //   projectId: 'prizm-oneidlab',
  //   databaseURL: 'https://prizm-oneidlab-default-rtdb.asia-southeast1.firebasedatabase.app',
  //   storageBucket: 'prizm-oneidlab.appspot.com',
  // );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjoFdSmbSDfgHlXPQgAqE1pWMoUeaoFz0',
    appId: '1:296859940615:ios:cb3280d3b134b7554bb7a2',
    messagingSenderId: '296859940615',
    projectId: 'prizm-oneidlab',
    databaseURL: 'https://prizm-oneidlab-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'prizm-oneidlab.appspot.com',
    iosClientId: '296859940615-17j1n9a6p99inqr95iequkmks456r7op.apps.googleusercontent.com',
    iosBundleId: 'com.oneidlab.prizmios',
  );
}
